language: node_js

node_js:
  - node
  - "8"
  - "10"
  - lts/*

services:
  - mongodb
  - redis-server

cache: yarn

env:
  - mongoServer=127.0.0.1:27017
  - redisHost=127.0.0.1

script:
  - "yarn test"
