language: node_js

node_js:
  - lts/*
  - node

services:
  - mongodb
  - redis-server

before_install:
  - docker pull nats
  - docker run -d --name nats-main -p 4222:4222 nats

cache: yarn

env:
  - mongoServer=127.0.0.1:27017 redisHost=127.0.0.1

script:
  - "yarn test"
